# Site settings
title: Cyberjutsu
baseurl: "/cyberjutsu" # the subpath of the site
url: "https://gnar1zard.github.io" # the base hostname & protocol 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/s
  - vendor/gems/
  - vendor/ruby/

# Outputting
permalink: /:year/:month/:day/:title/
paginate: 5 # amount of posts to show
paginate_path: "/page:num/"

# Plugins
gems:
  - jekyll-paginate
